### ISSUE TITLE
Good for nothing

### ISSUE THREAD

**Issue by surabibio** [microchip-pic-avr-solutions/microchip-iot-developer-guides-for-aws#13]
You cannot add a line of code and compile.
Microchip is just taking us for a ride.
### a piece of junk

**Comment by M65649** [comment]
Hello, 

Could you try to compile with XC8 version 2.32 or GCC? There were some changes for the newest version of the XC8 compiler where the standard library size increased quite a lot.

**Comment by surabibio** [comment]
Hi sorry for the rant. Found that this code base does not compile in GCC or XC8. The code generated from Atmel Start and avr-iot-aws-sensor-node-studio compile with GCC with any optimization including DEBUG and I am using them.

**Comment by surabibio** [comment]
I want to use Winc1510 with a third party microcontroller (RISCV) ultimately.
There seems to be two ways of obtaining the winc library.

1. From Atmel Start/Harmony/Github/Atmel Studio ASF 
2. From Microchip Library for Applications (MLA)

There are differences but not as different as it first appeared. 
My question is MLA under active development and will it support the current firmware version of Winc1510?

**Comment by M65649** [comment]
Hello, I'm not on the team working on the WINC, so you have to reach out to the support at https://microchipsupport.force.com/s/. Sorry for not having any other answer to this.
